# Initial OpenAPI v3 Specification - will be defined in I1.T4
# This is a placeholder file. Actual spec will be generated/defined in I1.T4.
openapi: 3.0.0
info:
  title: LLM-Powered SQL Query System API
  description: API for interacting with a PostgreSQL database using natural language.
  version: 0.1.0

paths:
  /api/v1/query:
    post:
      summary: Process Natural Language Query
      operationId: process_user_query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0.0.yaml#/components/schemas/ValidationError'

components:
  schemas:
    QueryRequest:
      title: QueryRequest
      type: object
      properties:
        query:
          title: Query
          type: string
          description: The natural language query from the user.
      required:
        - query
    QueryResponse:
      title: QueryResponse
      type: object
      properties:
        response:
          title: Response
          type: string
          description: The natural language response generated by the system.
      required:
        - response