# Example configuration file for the LLM-Powered SQL Query System

# Database configuration (can also be set via DATABASE_URL env var)
# database:
#   url: "postgresql://user:password@host:port/dbname" # Env var takes precedence

# LLM configuration (can also be set via env vars)
# llm:
#   api_key: "sk-your-openai-api-key" # Env var OPENAI_API_KEY takes precedence
#   model: "gpt-4o" # Env var LLM_MODEL takes precedence
#   temperature: 0.7 # Env var LLM_TEMPERATURE takes precedence

# Add other non-sensitive configuration here
# For example:
# logging:
#   level: INFO
#   format: json

# schema_caching:
#   enabled: true
#   ttl_seconds: 3600

# sql_error_correction:
#   max_attempts: 3